pihole:
  serviceDns:
    type: LoadBalancer
    port: 53
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.55

  serviceWeb:
    type: LoadBalancer    
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.56    
    http:
      enabled: true
      port: 80
    https:
      enabled: false

  envVars:
    TZ: "America/New_York"
    WEBPASSWORD: "your_secure_password"

  persistentVolumeClaim:
    enabled: true
    size: 1Gi

  DNS1: "8.8.8.8"
  DNS2: "8.8.4.4"