apiVersion: v2
name: home-assistant
description: Home Assistant deployment
version: 0.1.0
dependencies:
  - name: home-assistant
    version: 0.2.115
    repository: https://pajikos.github.io/home-assistant-helm-chart/